@echo off
echo Creating virtual environment...
python -m venv venv --upgrade-deps
echo Activating virtual environment...
call venv\Scripts\activate.bat
echo Installing dependencies...
pip install -r requirements.txt
echo Setup complete!
pause